export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const SAVE_CART_SHIPPING_ADDRESS = "SAVE_CART_SHIPPING_ADDRESS";
export const SAVE_CART_PAYMENT_METHOD = "SAVE_CART_PAYMENT_METHOD";
